### ISSUE TITLE
NPC's should initiate conversation when opened

### ISSUE THREAD

**Issue by PatrickMurphyDev** [PatrickMurphyDev/SnugStoryAI#87]
Currently: NPC Waits for you to initiate conversation after you open dialog
Desired Behavior: NPC Initiates conversation based on relationship, plot, and past conversations.

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modify GameMapScene.js and ConversationController.js to allow NPCs to initiate conversations based on relationship, plot, and past conversations.

You can review changes in this commit: https://github.com/mnmnk43434/PatrickMurphyDev-SnugStoryAI-87/commit/da4825cd8e7a7b8eaa562ca5b329e52e0046f078.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by PatrickMurphyDev** [comment]
on socket event open conversation, prompt AI
